### ISSUE TITLE
Implement Send for RoTxn

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/heed#191]
I wanted to make the write transactions `Send` but LMDB's documentation says:
> A write [Transaction](https://lmdb.readthedocs.io/en/release/#lmdb.Transaction) may only be used from the thread it was created on.

However, I think that making `RoTxn: Sync` with the `sync-read-txn` is not safe, but I may be mistaken. But, for sure, `RoTxn` should implement `Send`, since it can be moved to other threads safely.

**Comment by Kerollmops** [comment]
[According to the documentation](https://github.com/LMDB/lmdb/blob/c7b3cc4df6dfe8f0772fb509bdc74777667caa43/libraries/liblmdb/lmdb.h#L610-L618) it seems that you are right we can't refer to the read transaction from different threads, at least we must synchronize the use (by using a mutex?). [According to Howard Chu](https://github.com/CoreyKaylor/Lightning.NET/issues/44#issuecomment-72986781), we must remove this `sync-read-txn` feature and introduce the new `send-read-txn` feature you want to implement instead.

> **MDB_NOTLS**
>
> Don't use Thread-Local Storage. Tie reader locktable slots to #MDB_txn objects instead of to threads. I.e. #mdb_txn_reset() keeps the slot reserved for the #MDB_txn object. A thread may use parallel read-only transactions. A read-only transaction may span threads if the user synchronizes its use. Applications that multiplex many user threads over individual OS threads need this option. Such an application must also serialize the write transactions in an OS thread, since LMDB's write locking is unaware of the user threads.

### Yanking or Reporting a Security Issue?

I have some questions for the crates.io team or Rust developers in general, but should I yank all previous versions of the heed crate? Or should I raise an ICE about heed that concerns this specific `sync-read-txn` feature? The latter seems more appropriate as the library is safe to use until you use this particular feature.

Thank you for the investigation and report again 🙏

**Comment by Kerollmops** [comment]
Reopening as I need to fill a RustSec advisory.

**Comment by Kerollmops** [comment]
I just asked for help in https://github.com/rustsec/advisory-db/issues/1755, and we will continue the discussion there, closing.
