### ISSUE TITLE
expose mdb_env_set_flags()

### ISSUE THREAD

**Issue by mikedilger** [meilisearch/heed#202]
During migrations, I want to set NO_SYNC | NO_META_SYNC.
(yes I try to do it as one transaction anyways)

**Comment by Kerollmops** [comment]
Isn't the `EnvOpenOptions::flag` method not enough? It is available on the _0.20.0-alpha_ versions.

**Comment by Kerollmops** [comment]
Could you describe what you would like to do? If I had to open an env with specific options, I would use the `EnvOpenOptions` to set up the flags and use it the whole program. Are you trying to change the environment options when the env is already opened? If so, you could close it with [the `Env::prepare_for_closing` method](https://docs.rs/heed/0.20.0-alpha.4/heed/struct.Env.html#method.prepare_for_closing) and reopen it afterward.

**Comment by mikedilger** [comment]
I'm no longer doing this.  I *was* opening it without these options and syncing every transaction, then during certain sequences I wanted it to not sync every transaction.  Now I'm manually handling the syncing.
