### ISSUE TITLE
confusion when using the "range" operation

### ISSUE THREAD

**Issue by hxuchen** [meilisearch/heed#208]
While attempting to transition the database used in the [ord](https://github.com/ordinals/ord) to `lmdb`.
 I encountered confusion when using the `range` operation. 
When I tried using`&([u8; 44][..]..=[u8; 44[..]])`: [failed deom1](https://github.com/hxuchen/test_ord_with_heed/tree/failed_range), I received the error message `the size for values of type [u8] cannot be known at compilation time`.
 Similarly, when I utilized `&(&[u8; 44]..=&[u8; 44])`: [failed demo2](https://github.com/hxuchen/test_ord_with_heed/tree/failed_range2), I encountered the error message `the trait bound RangeInclusive<&[u8; 44]>: RangeBounds<[u8]> is not satisfied`.
 Eventually, I managed to complete the testing using [`iter demo`](https://github.com/hxuchen/test_ord_with_heed/tree/master). How should I modify my code to address these issues?

**Comment by hxuchen** [comment]
This should work
```struct RangeInclusiveArray<const N: usize>([u8; N], [u8; N]);

impl<const N: usize> RangeBounds<[u8]> for RangeInclusiveArray<N> {
    fn start_bound(&self) -> std::ops::Bound<&[u8]> {
        std::ops::Bound::Included(&self.0)
    }

    fn end_bound(&self) -> std::ops::Bound<&[u8]> {
        std::ops::Bound::Included(&self.1)
    }
}```

**Comment by Kerollmops** [comment]
Hey @hxuchen 👋

Is your last post exposing the solution to your problem? Have you found how to do it?

**Comment by hxuchen** [comment]
@Kerollmops 👋
Yes, I built this struct `struct RangeInclusiveArray<const N: usize>([u8; N], [u8; N]);`, and then implemented the `RangeBounds<[u8]>` trait for it. It resolved my issue and passed the tests.
