### ISSUE TITLE
Does the "database was previously opened with different types" error imply that the database might be corrupted?

### ISSUE THREAD

**Issue by hxuchen** [meilisearch/heed#210]
🙋
Does the ```database was previously opened with different types``` error imply that the database might be corrupted? 
When I exit the program, an error ```MDB_BAD_DBI: The specified DBI handle was closed/changed unexpectedly``` is thrown (likely during commit), and then every time I reopen and access this database, I see the ```database was previously opened with different types``` error.
 By the way, my original code didn't use ```env.prepare_for_closing().wait()```; I'm not sure if that's the reason the exception occurs upon program exit. 
If the database is indeed corrupted, are there any effective methods for repairing it?🙏

**Comment by hxuchen** [comment]
But when i using ``` env.prepare_for_closing().wait()``` [here](https://github.com/ABMatrix/ord/blob/9f6592cdb92a7ec12abba99473b0e9705ecb741c/src/lmdb_index.rs#L270), it blocks the exit.😂  Based on the [```wait```](https://docs.rs/heed/latest/heed/struct.EnvClosingEvent.html#method.wait),I seem to be unable to identify any remaining missed env at  this point.

**Comment by Kerollmops** [comment]
Hey @hxuchen 👋

Heed keeps the type the databases were opened with e.g. `Database<Str, SerdeJson<MyStruct>>`. So, when you try to open a database from the same `Env`, you get this error. It doesn't mean there is corruption but that you tried opening a known database with another type, e.g. `Database<U32, Str>`.
