### ISSUE TITLE
Make `RoIter` also `Send` when `read-txn-no-tls` feature is enabled

### ISSUE THREAD

**Issue by xiaoyawei** [meilisearch/heed#213]
With similar reasoning that `RoTxn` can be moved among threads when `MDB_NOTLS` flag is on, my understanding it that the corresponding `RoCursor` and `RoIter` (and other readonly iterators like range iterators) can be moved among threads as well, and hereby can implement `Send`.

By looking at the source code of `lmdb`, looks like [cursors is actually a field of a transaction](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L1335), and since different threads can access to the same db with the transaction pointer not simultaneously, they are also able to use a specific cursor in that transaction for data access.

I could be mistaken but would love to hear about opinions from `heed` maintainers. Thanks!

**Comment by Kerollmops** [comment]
I am pretty sure you are right, it seems to me that when `MDB_NOTLS` is enabled the transaction is not stored in a particular thread. Rust prevents us from touching the content of transaction (thanks `!Sync`) and therefore I am pretty sure that it is safe.

**Comment by Kerollmops** [comment]
Hey @xiaoyawei 👋

I will be working on that in a PR. Thanks [to your emails](https://www.mail-archive.com/openldap-technical@openldap.org/msg28428.html), we can make the cursors implement `Send`.

**Comment by xiaoyawei** [comment]
@Kerollmops That sounds great! My apologies for missing your previous comment but glad this idea can implemented, thanks!
