### ISSUE TITLE
dropping RwTxn

### ISSUE THREAD

**Issue by mikedilger** [meilisearch/heed#267]
I've assumed in my code that when RwTxn is dropped without a commit, that it would rollback.  Looking into the heed code I was surprised there is no Drop trait for RwTxn and now I'm not sure what my code is actually doing all over the place where `RwTxn`s fail to commit because of an early Result::Err return by a ?.'

Can you advise?

**Comment by Kerollmops** [comment]
Hey @mikedilger 👋

The `RwTxn` struct doesn't directly implement `drop` because it wraps an `RoTxn` which implements `drop` and `abort`s the transaction.

**Comment by bu5hm4nn** [comment]
So the answer is it's safe to drop `RwTxn` because the wrapped `RoTxn` will call `abort` and roll back?

**Comment by Kerollmops** [comment]
Yes, exactly. Rust drops the wrapped struct. Here, the `RoTxn` in a struct when the outer struct is dropped. So, the `RoTxn` will be dropped when the `RwTxn` is, and the behavior of the `RoTxn` drop is to abort the transaction.
