### ISSUE TITLE
`put` variant that returns the previous value for a key

### ISSUE THREAD

**Issue by guozirui33** [meilisearch/heed#279]
Hello! I was wondering if there exists a way to get the previous value for a key after calling `put`. Taking a look at https://docs.rs/heed/latest/heed/struct.Database.html#method.put, `put` simply returns a `Result<()>`. 

Would it be possible to have a variant `put_with_value` (my naming is terrible, I'm sure we could find a better name) that would return a `Result<Option<DC::EItem>>`? Or would this be difficult to do given the lifetimes attached to `put`?

**Comment by Kerollmops** [comment]
Hey @guozirui33 👋

Thank you for using heed. Unfortunately, heed is a wrapper on top of LMDB and LMDB doesn't allow to return the previous version of a value after a put.

The main reason is if two writes occurs on the same entry in the same transaction, the previous version is completely erased in memory.

However, a possible solution for you would be to provide a read txn and to do two fetches to return the version visible by the reader when you write in the write transaction. But it doesn't make sense if you write multiple times to an entry in the same write transaction before committing.

Another solution would be to allocate the key. Doing a read followed by a put in place. But I will not accept more allocations to this library.

**Comment by guozirui33** [comment]
Hi @Kerollmops , thank you for your response! Your explanation makes sense to me. I will use the read before put pattern then.
