### ISSUE TITLE
Support custom encoding/decoding errors

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/heed#88]
It would be better and easier to debug a program if the `BytesEncoding` and `BytesDecoding` traits could return any error type.

To do so we need to modify the `Error` enum and more specifically the `Encoding` and `Decoding` variants to wrap a `Box<dyn Error>`.

**Comment by MarinPostma** [comment]
funny, I spent 3 hours debugging an error caused by just that, where a serializing error occured in a `SerdeJson`...
